version: "3.2"

services:
  ### ELASTICSEARCH Container ###
  elasticsearch:
    image: elasticsearch:5.6.16
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - net-elasticsearch

  ### REDIS Container ###
  redis:
    build: ./core/images/redis
    container_name: redis
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - net-redis

### Networks Setup ###
networks:
  net-elasticsearch:
    driver: bridge
  net-redis:
    driver: bridge

### Volumes Setup ###
volumes:
  esdata:
    driver: local
  redisdata:
    driver: local