version: "3.2"

services:
  ### MYSQL Container ###
  mysql:
    platform: linux/amd64
    build: ./core/images/mysql
    container_name: mysql
    volumes:
      - type: volume
        source: db-mysql
        target: /var/lib/mysql
        volume:
          nocopy: true
      - ./core/conf/mysql/conf/my.cnf:/etc/mysql/my.cnf:ro
      - type: bind
        source: ./share-files
        target: /var/www/share-files
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - net-mysql

### Networks Setup ###
networks:
  net-mysql:
    driver: bridge

### Volumes Setup ###
volumes:
  db-mysql:
    driver: local